name: cinesmaracaibo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Firebase
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.2.2

  #Complemented
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/image/Logo.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/image/Logo.jpeg"
    background_color: "#368E9A"
    theme_color: "#368E9A"

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/